--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#090300"
foreground="#a5a2a2"
cursor="#a5a2a2"

-- Colors
color0="#090300"
color1="#db2d20"
color2="#01a252"
color3="#fded02"
color4="#01a0e4"
color5="#a16a94"
color6="#b5e4f4"
color7="#a5a2a2"
color8="#5c5855"
color9="#db2d20"
color10="#01a252"
color11="#fded02"
color12="#01a0e4"
color13="#a16a94"
color14="#b5e4f4"
color15="#f7f7f7"
